### ISSUE TITLE
Preview 時にdefault css の origin.css と github.css のパスが Not foundになる

### ISSUE THREAD

**Issue by sakunyo** [previm/previm#102]
https://github.com/previm/previm/blob/915745df95f1227ab0ec9b81f108d5fbc758751a/autoload/previm.vim#L64

上記の CSSのパスが `previm.css` からの相対パスで見えなくなったようです。

**Comment by koturn** [comment]
origin.cssとgithub.cssについては，
```vim
    call extend(css, ["@import url('../../_/css/origin.css');",  "@import url('../../_/css/lib/github.css');"])
```
とするのが正しいと思われます．

**Comment by mattn** [comment]
closed by #104
