### ISSUE TITLE
Mermaid subgraphs not supported

### ISSUE THREAD

**Issue by axsauze** [previm/previm#110]
Currently I try this graph which works correctly in the mermeid viewer but not in the plugin. Would it be possible to add support for subgraphs? 

Thanks.

#### Example graph:
```
graph TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
```

**Comment by helloworldcoding** [comment]
> Currently I try this graph which works correctly in the mermeid viewer but not in the plugin. Would it be possible to add support for subgraphs?
> 
> Thanks.
> 
> #### Example graph:
> ```
> graph TB
>     c1-->a2
>     subgraph one
>     a1-->a2
>     end
>     subgraph two
>     b1-->b2
>     end
>     subgraph three
>     c1-->c2
>     end
> ```

try this:
```mermaid
graph TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
```
