### ISSUE TITLE
[resolved]PrevimOpen does not work in Safari

### ISSUE THREAD

**Issue by aoi1** [previm/previm#137]
OS: mac OS Mojave
neovim: v 0.4.3
Safari: 13.0.3 (14608.3.10.10.1)

vimrc
```
let g:previm_open_cmd = 'open -a Safari'
```

When I execute command :PrevimOpen in neovim, the Browser opens and says "Loading... " and does not open the markdown file.

The javascript error says "Not allowed to load local resource: file:///Users/xxx/.cache/dein/repos/github.com/kannnokannno/previm/preview/xxxxxxx"

[How I resolved]

It was because of Safari browser.
You can open by using a different browser ex) Vivaldi
OR
Change the Safari Browser settings
Safari > Preference > Advanced > Show develop menu in menubar
and after checking it,
Develop > Disable Loacal File Restrictions

**Comment by mattn** [comment]
Thanks. I'll update README.md for Safari users.
