### ISSUE TITLE
Allow arbitally filetype to start previm

### ISSUE THREAD

**Issue by SinisterSoftware** [previm/previm#147]
previm.jsのfiletype判定にasciidoctorも追加して欲しい
adocのファイルタイプをasciidocではなくasciidoctorとするプラグインがあるので

**Comment by lambdalisue** [comment]
具体的にはどのプラグインでしょうか？どちらかというと asciidoc ではなく asciidoctor とするプラグイン側の問題かと思います。

**Comment by SinisterSoftware** [comment]
https://github.com/habamax/vim-asciidoctor
これです
確かに本来はasciidocとすべきなんでしょうね

**Comment by lambdalisue** [comment]
asciidoctor に限定しない形ならば一考の余地ありだと思うのでタイトルを変えました。

fyi.

https://github.com/previm/previm/blob/master/plugin/previm.vim#L30

**Comment by acodispo** [comment]
This would be useful to me too. I use Previm with Vimwiki (filetype vimwiki).

英語からのグーグル翻訳：これは私にも役立つでしょう。 PrevimとVimwiki（ファイルタイプvimwiki）を使用しています。
