### ISSUE TITLE
[Feature request] En and em-dash support

### ISSUE THREAD

**Issue by samarulmeu** [previm/previm#152]
Hello and thank you for this great plugin. 

Will it be possible to have support for en and em-dash support so that `--` converts to an en-dash (`–`) and `---` to an em-dash (`—`) as in LaTeX. 

Thank you!

**Comment by mattn** [comment]
Sorry for long delay. Could you please explain more description for your request?

**Comment by samarulmeu** [comment]
Using documents converters like `pandoc` or `lowdown` markdown text with `--` or `---` inside converts nicely to an en- and em-dash. I attached some pictures to explain. 

This is the markdown text:

![enEmDashVim](https://user-images.githubusercontent.com/39216570/174768416-0c699baa-b87b-4ecd-8eb4-fa1c22db796c.png)

Conversion done by `lowdown`

![enEmDashLowdown](https://user-images.githubusercontent.com/39216570/174768534-7535c7c4-9d46-4d53-a9b9-4edc2f1dfc00.png)

And this is how `previm` converts the same text

![enEmDashPrevim](https://user-images.githubusercontent.com/39216570/174768621-5a57e735-40d9-40bd-971d-8a6a1fb99aa9.png)

Hope this is clearer. 

Thank you even for the delayed answer.

**Comment by mattn** [comment]
Thank you for explaining. Please add your vimrc below.

```vim
let g:previm_extra_libraries = [
\  {
\    'name': 'typographer',
\    'files': [
\      {
\        'type': 'js',
\        'init': ['md.options.typographer = true;'],
\      },
\    ],
\  },
\]
```

**Comment by samarulmeu** [comment]
Thank you! It is working. Was some section in the documentation that I missed?

**Comment by mattn** [comment]
Now I added this on Wiki.

https://github.com/previm/previm/wiki/En-and-em-dash

Thank you.
