### ISSUE TITLE
[Bug] Check box list

### ISSUE THREAD

**Issue by samarulmeu** [previm/previm#153]
There is a problem in representing a check box item, as there is no space after the check box. 

For example, if you have this text

```
- [ ] item 1
- [x] item 2
- [ ] item 3
- [ ]  item 4
```

in the first three lines there is no space after the check box (see the picture). In case of item 4 you can get a space by having 2 spaces, but this I think contradicts a little bit the markdown philosophy. 

![items](https://user-images.githubusercontent.com/39216570/98095715-d26ef180-1e82-11eb-951a-1e743d82d017.png)

**Comment by mattn** [comment]
Closed by https://github.com/previm/previm/pull/157
