### ISSUE TITLE
Issues with local links post #187

### ISSUE THREAD

**Issue by ibhagwan** [previm/previm#203]
Introduced by https://github.com/previm/previm/commit/7e88ec859bedf6010684a496e38a14c73dd935bc.

Consider this local link:
```md
[Quickstart](#quickstart)
```

Before the above commit it would generate this (valid) link:
```
file:///<...path to cache...>/previm/preview/5f8a35655f499093-13127/index.html#quickstart
```

After this commit, the generated links is crafted using the actual local path (without the actual markdown file):
```
file:///<...path to actual source folder...>/fzf-lua/#quickstart
```

**Comment by KSR-Yasuda** [comment]
How about this?
Makes it ignore if the link path starts with `#`.

**Comment by ibhagwan** [comment]
> How about this? Makes it not handle as a local link if the link path starts with `#`.

Tested the change in #204, works as expected, ty @KSR-Yasuda!
