### ISSUE TITLE
特定パターンの文字列を含むプレビューで時間がかかります

### ISSUE THREAD

**Issue by hako-nya** [previm/previm#205]
括弧（[）+日付+文字列というパターンを含むファイルのプレビューで、通常に比べてプレビューに時間がかかることを確認しました。
例として、以下の文字列だけの markdown ファイルのプレビューに10秒程度かかります。また、その間 vim が一切操作できなくなり、vim のCPU使用率が跳ね上がります。
```
[1/30/2024 12:34:56ABCDEF
```

以下のように先頭の括弧を外すと、すぐにプレビューが表示されます。
```
1/30/2024 12:34:56ABCDEF
```

実行した環境は macOS、vim 9.0 の環境です。

Issue の報告が初めてなのですが、もし不足している情報などあればご指摘いただけますと幸いです。
よろしくお願いいたします。

**Comment by mattn** [comment]
手元で軽く書くにした限りでは再現しませんでした。
previm の動作を変えるためのオプションを付与されてますでしょうか。あれば教えて下さい。

**Comment by hako-nya** [comment]
ありがとうございます。previm のオプションは `g:previm_open_cmd` を設定していますが、他のオプションは設定していませんでした。

```
call plug#begin()
Plug 'previm/previm'
call plug#end()

let g:previm_open_cmd = 'open -a Google\ Chrome'
```

**Comment by beckorz** [comment]
私もWin+Chrome+Vim(8.2)環境確認しましたが、再現しませんね・・・
macOS環境でないと発生しない事象でしょうか・・・
macOS環境無くて悔しい

以前、以下のケースで、特定のmarkdown記述をすると、恐らくhighlihgt.js 側でハングアップしたケースは確認していますが、今回VimのCPU使用率が上がってるとの事なので、`:PrevimOpen` する前のprevim側に問題が予想でしょうか・・・
- https://github.com/previm/previm/issues/88

**Comment by mattn** [comment]
Chrome ではなく Vim の CPU 使用率が上がっているので、syntax 系な気がしています。
インストールされておられるプラグインを1つずつ外すなどして、どれが影響しているか確認頂けないでしょうか。
(二分探索的に探すと楽です)

**Comment by hako-nya** [comment]
ご報告が遅くなってしまい申し訳ありません。いただいたアドバイスを元に切り分けてみたのですが、previm以外のプラグインを全て外しても再現しました。また、Macvim（Vim 9.1）をインストールしてみたところ、こちらでは再現しないことが判明しました。
バージョン差異があるため明確な切り分けにはなっていないと思いますが、他の方で再現性がない状況を考えますと、おそらくバージョン依存ではなくmacOSにデフォルトで搭載されているvimに依存した問題なのかなと思います。

mattnさん、beckorzさん、ご協力いただきありがとうございました！
