### ISSUE TITLE
Local image reference is broken

### ISSUE THREAD

**Issue by KSR-Yasuda** [previm/previm#212]
Local image reference looks broken.

I think local paths used to be converted to point under the source file dir.
There would be some regression.

### Target Code

```text
![img](https://www.google.co.jp/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)

![img](googlelogo_color_272x92dp.png)
```

![PrevimImgRef_20241128_090159](https://github.com/user-attachments/assets/417eb725-c718-43c4-8f42-f1590d5204bd)

**Comment by KSR-Yasuda** [comment]
The commit 2a861ac5f1850e74cac1baccf85eabaec5dd4d43 makes this.

cf. #207

**Comment by KSR-Yasuda** [comment]
The commit looks related with the backslash escape issue reported as https://github.com/previm/previm/pull/211#issuecomment-2505099892

**Comment by lambdalisue** [comment]
Thanks. I revert that PR.

**Comment by KSR-Yasuda** [comment]
I'll close this PR.
If needed, we'd better discuss in #212 or such, since it is the degression of the commit.

**Comment by KSR-Yasuda** [comment]
@lambdalisue https://github.com/previm/previm/pull/211#pullrequestreview-2466298148

> Could you add test for this?

As for the test, I suppose you've dropped tests for the prior escape conversion introduced at the commit 2a861ac5f1850e74cac1baccf85eabaec5dd4d43.

The current test I saw in https://github.com/previm/previm/pull/211#issuecomment-2490085790 is just for `previm#convert_to_content()`, executed after the prior conversion, huh?
This old conversion has no charge, but preprocessed message had been transformed into the unintended.

So, you'd better consider about tests for it, if you rebuild it again
(I'm afraid it looks too hard for me to owe, though... Gosh, it's quite tough!).

What do you think?

**Comment by lambdalisue** [comment]
I thought this issue was resolved by reverting the PR. I haven't get enough time to test it but am I wrong?

**Comment by KSR-Yasuda** [comment]
Yes, now this is cleared.

It's just the reason why the test had overlooked the failure.
If you don't mind, just ignore it.

**Comment by KSR-Yasuda** [comment]
So, it's another problem to fixup the PR, then, I'd better close this issue too, hadn't I?
