### ISSUE TITLE
別のmarkdownの編集について

### ISSUE THREAD

**Issue by mattn** [previm/previm#44]
現状、index.html を previm/preview/index.html として生成していますが、これを例えばmarkdownのフルパスのハッシュ値で作れば同時に複数のmarkdownが編集出来るのではと思ったのですがどうでしょうか？
現状、プレビューファイルが1つなので同時に別のmarkdownを編集する事が出来ないです。
vim だと sha256 関数があるのでそれが使えるかもしれません。

**Comment by kannokanno** [comment]
なるほど、ありがとうございます！検討します。

**Comment by mattn** [comment]
対応済み。
