### ISSUE TITLE
コマンドprevimを実行してもブラウザが開かない。

### ISSUE THREAD

**Issue by shinji-kakimoto** [previm/previm#46]
:previmを実行するとブラウザが起動しません。また、エラーメッセージなども表示されません。
previm\preview\index.htmlを開いたまま、:previmを実行すると画面が更新されます。
現在、open-browser.vimを使って、ブラウザを起動していますが、連携がうまく行っていないのでしょうか？
既定のブラウザはIEです。

また、vimrcには下記を記載しています。
NeoBundle 'kannokanno/previm'
NeoBundle 'plasticboy/vim-markdown'
NeoBundle 'tyru/open-browser.vim'
mdファイルをmarkdownファイルタイプに変更する
autocmd BufRead,BufNewFile *.{text,txt,md} set filetype=markdown
"デフォルトブラウザに指定

環境は以下になります。
Windows7Professional
KaoriyaVim 7.4.1161 (2016/01/24版)

設定などが必要であれば教えて下さい。

**Comment by xxxkurosukexxx** [comment]
横からすみません。
open-browser.vimの[コミット:616949c](https://github.com/tyru/open-browser.vim/commit/616949c220235a4795b56c1b0b65d1bb6ed47a57)から連携がうまくいかなくなっているようです。

previm側のautoload/previm.vimの16行目を`call s:apply_openbrowser('file:///' . a:preview_html_file)`にしたら一応動くようになったのですが、プラグイン詳しくなくてこれで良いのか判断できないためコメントにて失礼します...。

**Comment by kannokanno** [comment]
@xxxkurosukexxx 
ありがとうございます！
私の環境(OSX 10.11.3)では再現せず、とても助かります。

@shinji-kakimoto 
以下のようにブランチを切り替えて試して頂けますでしょうか。

1. vimrcを変更

  ```vim
  " この部分を変更
  " NeoBundle 'kannokanno/previm'
  NeoBundle 'kannokanno/previm', '46-support-latest-open-browser'
  ```

1. `NeoBundleInstall`を実行(`NeoBundleUpdate`だったかもしれません)
1. Vimを再起動
1. markdownのファイルを開いて`:PrevimOpen`を実行

**Comment by tyru** [comment]
自分の環境ではprevimとopen-browser.vimの最新版で動いているようです。
設定はどちらもコメントアウトしました。

OS: Linux
previm: https://github.com/kannokanno/previm/commit/b130f24277e3c6a5afa3984921516b0a83b31d28
open-browser.vim: https://github.com/tyru/open-browser.vim/commit/8b342c9977e82becd8cbfabe5c453043bcd72395

@kannokanno 
ちなみに `g:openbrowser_open_filepath_in_vim` より `file:///` 付けてもらった方が確実です。
色々考えててこれから廃止予定でいます(といっても現状では動く想定なのですが…)。
https://github.com/tyru/open-browser.vim/issues/1

**Comment by kannokanno** [comment]
@tyru ありがとうございます！

> ちなみに g:openbrowser_open_filepath_in_vim より file:/// 付けてもらった方が確実です。

なるほど。
では今回の件がこれで解決するかどうかとは関係なく、`file:///`を付けるように修正するのが良さそうですね :muscle:

**Comment by shinji-kakimoto** [comment]
@kannokanno さん
対応有難うございます。
previmのBranchを切り替え、指定された手順で実施しました。
が、ブラウザは起動せず、挙動は何も変わりませんでした。
既定ブラウザをIEで指定していましたが、FireFoxでの実施も試みましたが、こちらもダメでした。

open-browser単体ではURLを開くことができますが、previmとの連携がうまく行きません。
@xxxkurosukexxx さんの環境では動いているということなので、私の環境設定の問題な気がしてきました。
プラグインに詳しくなく追いきれていませんが。

簡単ですが、現状報告です。

**Comment by Bakudankun** [comment]
自分の環境（Windows 10 / Vim-KaoriYa / previm, open-browser 共に最新）でも`:PrevimOpen`でブラウザが開かなくなってはいたのですが、`46-support-latest-open-browser`を指定したところ、こちらでは正常にブラウザが開くようになりました。
しかしvimrcで`shellslash`を設定していたので、Markdownファイルを開いて最初に`:PrevimOpen`する前に`:set noshellslash`したところ、またブラウザが開かなくなりました。
Windowsではデフォルトでshellslashがオフなので、このあたりが原因かもしれません。

Windowsでの今のところの対症療法としては、vimrcで`set shellslash`しておくか、もしくは`:PrevimOpen`する前に`:set shellslash`する（一度`:PrevimOpen`した後では無駄でした）こと、でしょうか。

**Comment by shinji-kakimoto** [comment]
@Bakudankunさん
情報ありがとうございます！
`:PrevimOpen`実行前に`:set shellslash`を設定するとブラウザが開くようになりました。
また、`:PrevimOpen`実行後に`:set shellslash`を設定すると、こちらでもブラウザは起動しません。

**Comment by xxxkurosukexxx** [comment]
@kannokanno さん
早急なご対応ありがとうございます！
私の方でも`46-support-latest-open-browser`で問題なく開けることを確認しました。
環境書き忘れててすみません、Windows7 / Kaoriya-Vim です。

@Bakudankun さん
なるほど、たしかに私の.vimrcでも`set shellslash`してました。

**Comment by kannokanno** [comment]
返信遅くなりました :bow: 

@Bakudankun 
ありがとうございます！調査頂きまして、とても助かりました。
なるほど `shellslash` ...。

@shinji-kakimoto 
状況の記載ありがとうございます！
すぐに取り掛かれないのですが、根本的な対応をしたいと思います。

@xxxkurosukexxx 
環境の記載ありがとうございます！

**Comment by kannokanno** [comment]
@shinji-kakimoto @Bakudankun @xxxkurosukexxx 
とりあえず `46-support-latest-open-browser` をmasterにmergeしました。
(返信は特に不要です)

**Comment by washon** [comment]
こんにちは。横から失礼します。

Windows7 / Kaoriya vim / Previm / open-browser
の私の環境では、file///だけではなく、``s:base_dir``のパスにバックスラッシュが入っていても
open-browserがうまく動いてくれませんでした。

暫定的ではありますが、当該の場所でバックスラッシュをスラッシュに置換してみました。
他の環境では調査不十分で、暫定的な対処ではありますが、プルリクエストを作成しておきました。

ご対応よろしくお願いいたします。

**Comment by mattn** [comment]
こちらの修正、既にマージされています。一旦 close しますのでまだ問題が残っていれば reopen して下さい。
