### ISSUE TITLE
ローカルの画像を参照できない

### ISSUE THREAD

**Issue by kannokanno** [previm/previm#5]
残念

**Comment by narugit** [comment]
ローカルの画像が参照できないのですが，よろしければご教授頂けないでしょうか．

**環境**
・Windows 10
・Git-Bash
・tyru/open-browser.vimを使用

**ディレクトリ構成**
```
hoge/
  |- fuga.md
  |- piyo.jpg
```

**参照方法**
いずれも参照できませんでした．
```
![Alt Text](./piyo.jpg)

![Alt Text](piyo.jpg)  

<img src="./piyo.jpg">  

<img src="piyo.jpg">  
```

**スクリーンショット**
![screenshot](https://user-images.githubusercontent.com/28133383/43520127-d5b3c078-95cc-11e8-94d8-6f31562cd299.png)


何卒，よろしくお願い致します．

**Comment by beckorz** [comment]
試しに

set shellslash

して:PrevimOpenしてもらえますか？

たぶん
//localhost/C://Users//user//Desktop//hoge/./piyo.jpg
//localhost/C:%5CUsers%5Cuser%5CDesktop%5Choge/./piyo.jpg

の/エスケープ周りが関係してそうですね。

**Comment by narugit** [comment]
@beckorz 
ご返信ありがとうございます．

`set shellslash`を.vimrcに記入後，
:PrevimOpen
してみましたが，結果は同じでした．

## 実行結果

### 条件1
- `set shellslash`を.vimrcに記入
- :PrevimOpenで起動

#### スクリーンショット
![SetShellSlashConsole](https://user-images.githubusercontent.com/28133383/43676536-5f75a930-982e-11e8-9ef0-59fa2b3c774f.PNG)
![SetShellSlashSources](https://user-images.githubusercontent.com/28133383/43676537-5fa2782a-982e-11e8-8829-4d86fd66bd7a.PNG)


### 条件2
- `set shellslash`を.vimrcに記入せず
- :PrevimOpenで起動

#### スクリーンショット
![NoSetShellSlashConsole](https://user-images.githubusercontent.com/28133383/43676519-028fca5c-982e-11e8-8b37-7ab817f6c7b7.PNG)
![NoSetShellSlashSources](https://user-images.githubusercontent.com/28133383/43676524-1a59979e-982e-11e8-8ea5-613ac919b7da.PNG)

**Comment by beckorz** [comment]
git-bashの環境ですね。
プレビュー時のファイルパスが\ではなく、/なのですね。
ちょっと確認してみます。
ちなみに、Chromeの開発ツールのElementsで、上の二つの例示のパスを見るとどうなってますかね?

ちなみに、previmの仕様上imgタグで相対的に指定したローカルファイルのイメージファイル参照は出来ないので、例示されている下の二つは表示できない仕様です。
仕組み上previmはプレビュー表示する際に、[](./)な相対パスな画像ファイルは、絶対パスに置き換えて表示する仕様になっています。

**Comment by narugit** [comment]
@beckorz 
早速のご返信ありがとうございます．

はい，git-bashの環境でございます．
仕様も教えてくださり，ありがとうございます．

.vimrcに`set shellslash`を記入した状態でも記入していない状態でもChromeの開発ツールのElementsにおいて，画像のパスが同一であったため，.vimrcに'set shellslash'を記入した状態のスクリーンショットを示します．

![SetShellSlash](https://user-images.githubusercontent.com/28133383/43677092-61f0c47a-9837-11e8-8281-61964dce75e0.PNG)

**Comment by narugit** [comment]
@beckorz 

imgタグに絶対パスを記入することでローカル画像が表示されました．
ちなみに，.vimrcに`set shellslash`が記入された場合，されていない場合の両方でローカル画像が表示されました．

この度は，誠にありがとうございました．

**スクリーンショット**
![imgTagWithAbsolutePath](https://user-images.githubusercontent.com/28133383/43677341-47f2a0b2-983b-11e8-8bb7-2846a1116433.PNG)

**Comment by narugit** [comment]
@beckorz 
関数previm#relative_to_absolute_imgpath内で
```
let dir = substitute(a:mkd_dir, '\\\\', '/', 'g')
let elem.path = substitute(elem.path, '\\\\', '/', 'g')
```
とすることで，所望の動作を確認しました．

**スクリーンショット**
![](https://user-images.githubusercontent.com/28133383/43677794-183df332-9843-11e8-8c29-74d1e5ad75b9.PNG)

**Comment by beckorz** [comment]
なるほど。了解です。
やはりbackslashのエスケープが上手くできていない感じですね。
私の方でgit-bashの環境のvimを使ったらvim自体がうまく動かずに嵌っておりました。
ただ、ここらへんのソースが複数の環境があり、何が最適なのか把握しきれていませんが、
問題なさそうだったらPRを考えてみてはどうでしょう？

**Comment by narugit** [comment]
@beckorz 
お手数をお掛けしました．
本当にありがとうございます🙇 

かしこまりました．
他の環境での動作も確認してみて，PRも考えてみますね．
