### ISSUE TITLE
supports for latex style math command

### ISSUE THREAD

**Issue by chantisnake** [previm/previm#56]
insert inline math with $ \some_math_here $ 

insert block math with $$ \math_block $$

**Comment by chowzepeng** [comment]
The LaTeX feature doesn't work in my laptop, no matter trying 
- `$\sigma$`,
-`$\sigma$ 
- or by inserting <script type="text/javascript"
   src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js">
    </script>
 could you add this feature in it?

**Comment by mattn** [comment]
Now supported loading extra libraries. See `:help previm-extra-libraries` and https://github.com/previm/previm/wiki/KaTeX
