### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by delijati** [previm/previm#66]
index.html not created for `rst` and `md`.
- NVIM 0.2.0-dev
- rst2html.py (Docutils 0.12 [release], Python 3.5.2+, on linux)

**Comment by mattn** [comment]
Did you get something errors?

**Comment by nagase00** [comment]
Same situation occurred.
URL to be created is incorrect.

file:///C:/Program%20Files/Vim/.vim%C2%80kbundle/previm/preview%C2%80kbd9267bc307198d7-11180/index.html

「%C2%80k」 what is it?

**Comment by mattn** [comment]
What version of Vim do you use?

**Comment by mattn** [comment]
I don't reproduce this on Windows7.

**Comment by yellowglasses20** [comment]
same error occurred.
The css and js folders are created.
But index.html not copied.

file:///C:/Program%20Files/tool/.vim/bundle/previm/preview/2ed26f43f31b074e-6560/index.html
index.html is not found.

**Comment by yellowglasses20** [comment]
Thank you for fixing.
I confirmed that it will work with the new version. :+1:

**Comment by mattn** [comment]
If you still have an issue, please file new issue.
