### ISSUE TITLE
Cannot put two images in one table row

### ISSUE THREAD

**Issue by kenzht** [previm/previm#70]
you can put images in one row, but cannot put more than two in one row.
In the following example, only the first image shows up, but not the next one. It's probably because only the first image tag is handled within a line or something.

| Example | Example |
|---|---|
|![aaa](aaa.PNG)|![bbb](bbb.PNG)|

**Comment by kannokanno** [comment]
Thank you for the report.
I want to fix it later.

**Comment by mattn** [comment]
This should be fixed already. So closing. If you still have issue, please reopen.
