### ISSUE TITLE
A way to export to pdf ?

### ISSUE THREAD

**Issue by lds-lds** [previm/previm#81]
Hello 
is there an integrated solution in previm to export the markdown file with mermaid code in pdf or odt?
here is my very short md code for exemple :
## hello
mermaid exemple
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C

**Comment by kannokanno** [comment]
Hi.
Sorry, I do not know 😞

**Comment by letientai299** [comment]
I've wrote a [guide for render PDF from markdown that using mermaid](https://gist.github.com/letientai299/2c974b4f5e7b05be52d369ff8693c29a). Hope that help.

**Comment by mattn** [comment]
This is not an issue of previm. Sorry.
