### ISSUE TITLE
[Feature Request] Floating table of content

### ISSUE THREAD

**Issue by letientai299** [previm/previm#84]
It's would be extremely useful to have a floating table of content for long document.

Example screenshot (take from [vuejs doc](https://vuejs.org/v2/guide/))

![image](https://user-images.githubusercontent.com/8386780/36932510-ecfce942-1f04-11e8-9b14-b9f7b502c993.png)

**Comment by kannokanno** [comment]
Hi.
That's a good idea.
But now I do not have time to add features 😢

**Comment by mattn** [comment]
Added how to add toc list on Wiki.

https://github.com/previm/previm/wiki/MarkdownItAnchor
