### ISSUE TITLE
How to change axis format in gantt diagram?

### ISSUE THREAD

**Issue by RidaAyed** [previm/previm#87]
Hi

Any idea how the axis format could be changed?

Trying this line in the bottom snippet changes the gantt to blank, though I'd expect the axis to be changed:

`axisFormat  %m/%d/%Y`

	```mermaid
	gantt
	    title MyTitle
	    dateFormat  YYYY-MM-DD
	    axisFormat  %m
	    section Region A
	    Milestone 1       :a1       , 2018-01-01 , 15w
	    Milestone 2       :a2       , after a1   , 15w
	    Milestone 3       :after a2 , 15w
	```

https://github.com/knsv/mermaid/issues/269

**Comment by beckorz** [comment]
Hi.

I confirmed the problem.
It is supported by mermaid.js 8.0.0. And now I am pull request. #130 

![GanttDiagram01](https://user-images.githubusercontent.com/790009/54095496-06162180-43eb-11e9-87ce-74bf46667b83.png)
![GanttDiagram02](https://user-images.githubusercontent.com/790009/54095500-09111200-43eb-11e9-82ea-6b340f8f6e93.png)

**Comment by mattn** [comment]
Closed by https://github.com/previm/previm/pull/130
