### ISSUE TITLE
markdown-it がハングする

### ISSUE THREAD

**Issue by mattn** [previm/previm#88]
おそらく markdown-it の少し古いバージョンで発生すると思うのですが以下の Markdown を食わせるとブラウザがハングします。

    ```
    |-------------------------------------------------|
    |-------------------------------------------------|
    ```

新しい markdown-it で直ってる事を確認したいのですが、lib 配下のファイルは手で更新されておられるのでしょうか？それともどこかに更新手順はまとまってますでしょうか？

**Comment by kannokanno** [comment]
手で更新しています！特に手順はありません 🙇

**Comment by mattn** [comment]
いえ、お手間でなければどの URL から取得しているか教えて貰っていいですか。
簡単なら更新スクリプト書きます。

**Comment by kannokanno** [comment]
ちょっと勘違いしていました。
markedの記憶で「手で更新している」と書きましたが、 #71 でmarkdown-itにご対応頂いたんでした。

@lambdalisue こちら取得元のURL、もしくは方法って覚えていますでしょうか？

**Comment by mattn** [comment]
ちなみに最新版では再現してない様です。

https://markdown-it.github.io/

ここで↑のコード記法を貼って確認しました。

**Comment by lambdalisue** [comment]
もともと手動更新っぽかったので、それに従って手動で入れています（たしか公式のzipかなにか）。

**Comment by beckorz** [comment]
こちらの方、別件で highlight.js 周りの動作確認してたところで、気になったので確認しました。

1. https://markdown-it.github.io/ の js に差し替え→ NG 
2. highlight.js を取り除く → OK
3. highlight.js の最新バージョン(v9.15.5)に差し替え → OK

上記のようなので各種ライブラリを最新にしてみて動作確認して、previmに修正をかけようと思います。
どのhighlight.jsのバージョンで修正が入ったのか気になりますが、とりあえず報告まで。

**Comment by mattn** [comment]
ありがとうございます。
