### ISSUE TITLE
previmを他の方にお譲りしたい

### ISSUE THREAD

**Issue by kannokanno** [previm/previm#91]
最近は自分の事業で忙しく、previmのメンテナンスに時間を割く余裕がありません。
せっかく頂いたissueやprにも、申し訳ないことにほとんど気が回らない状態です。

なので希望者がいたらprevimをお譲りしたいです。
ただこういう時の慣例というかフローが良く分かっておらず...。

引き取りたいという方がいましたら、このissueにてご連絡ください。
最低限の条件はissue/prで上がってくる英語にも一応対応できること、ぐらいです。

**Comment by mattn** [comment]
原稿を執筆するのに常用していて、けっこう生命線になりつつあります。

もし他の方で強い希望を持った方がいらっしゃらなければ開発を引き取らせて頂けないでしょうか。その際、私にでなく previm という org を作らせて頂こうかと思います。そして開発したいメンバを何人か入れられればと思います。

**Comment by mattn** [comment]
もし kannokanno さんがお好みなら previm の org でなく vim-jp で引き取る事も可能です。お好きな方を選んでください。

**Comment by kannokanno** [comment]
ありがとうございます！
previmのorg助かります。移行しようとしたのですが、権限エラーになってしまいました。
調べたところ、移行先(previmのorg)に僕を管理者として指定して頂く必要がありますでしょうか？

![image](https://user-images.githubusercontent.com/708123/42956996-537b3222-8bbc-11e8-8811-f2d67e1ad5f3.png)

**Comment by mattn** [comment]
invite しました。移行後、メールの流量などが辛い様であれば previm から leave 頂いても構いません。

なお開発の際は、著作者は kannokanno さん、メンテナとして previm organization とさせて頂きます。

**Comment by kannokanno** [comment]
ありがとうございます。移行できました！

> なお開発の際は、著作者は kannokanno さん、メンテナとして previm organization とさせて頂きます。

こちら承知しました。よろしくお願いします。

**Comment by lambdalisue** [comment]
previm.org 興味あります！超お世話になってるので

**Comment by mattn** [comment]
移行しました。
